server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/yurisanchezrojas/microservicios-tutorial/tree/eureka
          search-paths: config-data
  application:
    name: config-service